### ISSUE TITLE
不知道有沒有打算把新的週票房也套用進來

### ISSUE THREAD

**Issue by alanetsai** [kimballXD/box_office#3]
國家電影中心12月起改成「每週票房公告」了，格式好像還是一樣爛XD

**Comment by kimballXD** [comment]
正在改。然後因為周資料多公佈了本期數據 (本期票數、本期銷售額)，故之後的資料應該會分成兩份。一份是累計數據，一份是每一期歷史數據的推移(可以作右肩率之類的統計....)

這次改版把原本檔案裡每筆資料的 row number拿掉了，讓資料變成非常難 parsing，parse 錯的機率提高很多。之後據說會把 row number 放回來.....希望如此啦orz

**Comment by kimballXD** [comment]
恩……其實滿久以前就改好了，改成每週票房之後多了一些資訊，為了保持兼容性，parsing 完的檔案輸出成兩種版本(i.e.: 現況檔和歷史檔），就按需要取用囉。
